name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvnw.cmd clean install

    - name: Download ChromeDriver
      run: Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE" -OutFile "LATEST_RELEASE"

    - name: Install ChromeDriver
      run: |
        $VERSION = Get-Content -Raw -Path "LATEST_RELEASE"
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$VERSION/chromedriver_win32.zip" -OutFile "chromedriver.zip"
        Expand-Archive -Path "chromedriver.zip" -DestinationPath "$env:USERPROFILE"
        Remove-Item "chromedriver.zip"

    - name: Run Selenium tests
      run: mvnw.cmd test






# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path




    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
